export const mockHistoryData = [
  {
    id: "1",
    date: "11-01-2025 3:15:10 PM",
    user: "Karim",
    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "2",
    date: "11-01-2025 3:15:10 PM",
    user: "Rahim",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "3",
    date: "11-01-2025 3:15:10 PM",
    user: "Moni",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "4",
    date: "11-01-2025 3:15:10 PM",
    user: "Karim",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "5",
    date: "11-01-2025 3:15:10 PM",
    user: "Rahim",
    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "6",
    date: "11-01-2025 3:15:10 PM",
    user: "Moni",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "7",
    date: "11-01-2025 3:15:10 PM",
    user: "Karim",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "8",
    date: "11-01-2025 3:15:10 PM",
    user: "Rahim",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "9",
    date: "10-01-2025 2:45:30 PM",
    user: "Sarah",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "10",
    date: "10-01-2025 1:20:15 PM",
    user: "Ahmed",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "11",
    date: "10-01-2025 11:30:45 AM",
    user: "Lisa",
    status: "Draft" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: true,
    doc: false,
    print: false,
  },
  {
    id: "12",
    date: "09-01-2025 4:55:20 PM",
    user: "David",
    status: "Active" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: true,
    doc: false,
    print: true,
  },
  {
    id: "13",
    date: "09-01-2025 3:10:35 PM",
    user: "Maria",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: false,
    doc: true,
    print: false,
  },
  {
    id: "14",
    date: "09-01-2025 1:25:50 PM",
    user: "John",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "15",
    date: "08-01-2025 5:40:10 PM",
    user: "Emma",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: true,
    doc: false,
    print: true,
  },
  {
    id: "16",
    date: "08-01-2025 2:15:25 PM",
    user: "Alex",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: true,
    print: false,
  },
  {
    id: "17",
    date: "08-01-2025 10:50:40 AM",
    user: "Sophie",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "18",
    date: "07-01-2025 6:20:55 PM",
    user: "Michael",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: true,
    doc: false,
    print: false,
  },
  {
    id: "19",
    date: "07-01-2025 3:35:15 PM",
    user: "Anna",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: false,
    doc: true,
    print: true,
  },
  {
    id: "20",
    date: "07-01-2025 12:45:30 PM",
    user: "Robert",
    status: "Active" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: true,
    doc: true,
    print: false,
  },
  {
    id: "21",
    date: "06-01-2025 4:10:45 PM",
    user: "Elena",
    status: "Draft" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "22",
    date: "06-01-2025 1:55:20 PM",
    user: "James",
    status: "Active" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "23",
    date: "06-01-2025 11:25:35 AM",
    user: "Nina",
    status: "InActive" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: true,
    doc: true,
    print: false,
  },
  {
    id: "24",
    date: "05-01-2025 5:30:50 PM",
    user: "Peter",
    status: "Delete" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "25",
    date: "05-01-2025 2:40:15 PM",
    user: "Grace",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: true,
    doc: false,
    print: true,
  },
  {
    id: "26",
    date: "05-01-2025 10:15:30 AM",
    user: "Lucas",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: true,
    print: false,
  },
  {
    id: "27",
    date: "04-01-2025 4:50:45 PM",
    user: "Olivia",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "28",
    date: "04-01-2025 1:20:20 PM",
    user: "Daniel",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "29",
    date: "04-01-2025 11:35:55 AM",
    user: "Isabella",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: true,
    doc: true,
    print: false,
  },
  {
    id: "30",
    date: "03-01-2025 3:25:40 PM",
    user: "William",
    status: "Active" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: true,
    doc: false,
    print: true,
  },
  {
    id: "31",
    date: "03-01-2025 12:10:15 PM",
    user: "Zoe",
    status: "Draft" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "32",
    date: "03-01-2025 9:45:30 AM",
    user: "Benjamin",
    status: "Active" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: true,
    doc: false,
    print: false,
  },
  {
    id: "33",
    date: "02-01-2025 5:20:45 PM",
    user: "Chloe",
    status: "InActive" as const,
    export: "Single" as const,
    pdf: false,
    csv: false,
    xls: false,
    doc: true,
    print: true,
  },
  {
    id: "34",
    date: "02-01-2025 2:55:20 PM",
    user: "Ryan",
    status: "Delete" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "35",
    date: "02-01-2025 11:30:35 AM",
    user: "Mia",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: true,
    doc: true,
    print: false,
  },
];
